ALTER TABLE cards ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS previous_value DOUBLE PRECISION;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS value_changed_at TIMESTAMP;
